services:
  postgres:
    build: .
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - py_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  server:
    build: .
    container_name: server
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      UPLOAD_DIR: ${UPLOAD_DIR}
      QUEUE_NAME: ${QUEUE_NAME}
      QUEUE_EXCHANGE: ${QUEUE_EXCHANGE}
      QUEUE_KEY: ${QUEUE_KEY}
      BROKER_USER: ${BROKER_USER}
      BROKER_PASS: ${BROKER_PASS}
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"








volumes:
  rabbitmq_data: {}
  pg_data: {}